# Generated by Django 6.0.3 on 2026-04-16 14:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('master_admin', '0012_event_child_event_target_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='child_event_target_count',
        ),
        migrations.RemoveField(
            model_name='event',
            name='parent_event',
        ),
    ]
