# Generated by Django 6.0.3 on 2026-04-16 06:08

import django.db.models.deletion
import master_admin.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('username', models.CharField(max_length=150, unique=True)),
                ('email', models.CharField(max_length=255, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('role', models.PositiveSmallIntegerField(choices=[(1, 'User'), (2, 'Admin')], default=2)),
            ],
            options={
                'abstract': False,
            },
            managers=[
                ('objects', master_admin.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('fromDate', models.DateField(blank=True, null=True)),
                ('toDate', models.DateField(blank=True, null=True)),
                ('year', models.IntegerField(blank=True, null=True)),
                ('is_fixed', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('totalUserAllocated', models.IntegerField(default=0)),
                ('totalAmount', models.DecimalField(decimal_places=0, max_digits=15)),
                ('fromDate', models.DateField()),
                ('toDate', models.DateField()),
                ('year', models.IntegerField(default=2026)),
                ('is_adhoc', models.BooleanField(default=False)),
                ('approval_status', models.PositiveSmallIntegerField(choices=[(1, 'Chờ duyệt'), (2, 'Đã duyệt'), (3, 'Không duyệt')], default=2)),
            ],
        ),
        migrations.CreateModel(
            name='EventCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='master_admin.category')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='master_admin.event')),
            ],
        ),
        migrations.AddField(
            model_name='event',
            name='categories',
            field=models.ManyToManyField(through='master_admin.EventCategory', to='master_admin.category'),
        ),
    ]
